# Generated by Django 6.0.3 on 2026-03-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
